### ISSUE TITLE
The search is broken

### ISSUE THREAD

**Issue by vvep** [protomorph/astro-zero#14]
On localhost it seems there is no problem, but after I deploy to Cloudflare Pages, the search function doesn't work. The parameters in URL changed but search results do not appear and say 0.

https://arizky.pages.dev/search
https://arizky.pages.dev/search/?q=Zero
See video: https://files.getimiskon.xyz/f/jwa2i/x22r4.mp4

**Comment by protomorph** [comment]
looks like it can't load the json file for the search, i'll look in to this and see what needs changing

**Comment by prakash1763** [comment]
I just realized hopefully it will be fixed soon

**Comment by protomorph** [comment]
This should be ok now
