### ISSUE TITLE
Adding open graph image

### ISSUE THREAD

**Issue by prakash1763** [protomorph/astro-zero#15]
Hello sir thanks for the awesome starter template, clean, no style, and less framework. I want to ask how to add `og:image` and `twitter:image` meta tag on a page that does not contain a blog post? Like in home page, there doesn't seem to be any open graph and twitter card image. I see only blog posts that have it

**Comment by protomorph** [comment]
Thanks for the positive comment, I'll look at adding og meta tags to other pages and have commit done asap

**Comment by protomorph** [comment]
@prakash1763 sorry this has taken so long, just to let you know that you can pass an open graph image to the base template via an image attribute on your page template `<Base image="/path/to/image">`, hope that helps

**Comment by prakash1763** [comment]
Thak you!

**Comment by prakash1763** [comment]
Sorry sir, why I can't use image from local in MDX? Only image from external link is accepted
```
// src/content/posts/post-1.mdx
---
title: 'I am the title'
description: 'Some description.'
pubDate: 2024-06-28
image: '/assets/example.jpg'
category: 'Astro'
tags: ['html', 'framework']
featured: true
---

## Some text here
```
The image is located in `public/assets` folder

![Screenshot_2024-08-30-14-20-20-291](https://github.com/user-attachments/assets/8c3bca44-4fd8-4650-940b-022eb4937c7b)
Cause:
```
{
  "code": "ERR_INVALID_URL",
  "input": "/assets/example.jpg"
}
```

**Comment by protomorph** [comment]
@prakash1763 is the image in the public folder, that could be why it can't find it

**Comment by prakash1763** [comment]
Yes it is in the public folder also in src, still not working

**Comment by protomorph** [comment]
Hmm, that's odd, I'll look into why it can't find local images

**Comment by protomorph** [comment]
@prakash1763 @bcz3 this issue should be fixed now, the Image component was only allowing remote images due to the `inferSize` attribute being used, sorry about taking so long to fix this
