### ISSUE TITLE
Duplicated Breadcrumbs

### ISSUE THREAD

**Issue by bcz3** [protomorph/astro-zero#16]
Hi,
I found a minor issue with the breadcrumbs: there is a duplication when visiting paginated pages.

For example:

On `localhost:4321/blog`, the breadcrumbs are:
1. Home
2. Blog

On paginated `localhost:4321/blog/2`, the breadcrumbs are:
1. Home
2. Blog
3. Blog

**Comment by protomorph** [comment]
Thanks for spotting that, I'll work on a fix for it asap
